### ISSUE TITLE
driver is really slow

### ISSUE THREAD

**Issue by inecho** [KumarRobotics/flea3#27]
Recently i installed this driver and i actually find it really great, but i was wondering why the frame rate is so slow. By using two flea3 cameras i get an avg frame rate of 3Hz whereas by using the [original pointgrey driver](https://github.com/ros-drivers/pointgrey_camera_driver) i get around 15Hz. Im still preferring your package, because it is really stable and without dropouts for the cost of time lags up to 2 seconds.. is there any good explanation for that behavior?

**Comment by versatran01** [comment]
Is this issue happening all the time or just occasionally? 
Possible reasons: 
1. usbfs issue 
2. not enough current 
3. use usb3 instead of usb2

**Comment by inecho** [comment]
It is happening all the time, systematically. They are both gigE cameras and they also get unlimited current

**Comment by versatran01** [comment]
This driver is not designed for gige cameras, therefore I'd recommend that you use the original one.

**Comment by inecho** [comment]
Well, the your driver is still performing better than the original one. 
I made some test datasets to vizualize the performance issue in both. When im using an imu(300Hz), odometry(300Hz), velodyne(20Hz) and a tracker(10Hz) i have no problems to sample the data. As soon as i connect one or both cameras i get timeouts. Using your driver they are about 1sec and with the original one about **20sec**! this is really a pain... and may affect other users too.

Maybe you have a guess why i get those timeouts. What is different in your code?

This image shows the recordings with flea3-driver
![timeout-flea3driver](https://user-images.githubusercontent.com/25886425/44420564-92abe000-a57e-11e8-88d2-30921e4823d7.png)

Recordings with pointgrey_camera_driver
![timeout-ptgrey-driver](https://user-images.githubusercontent.com/25886425/44420565-92abe000-a57e-11e8-82f5-4ac2cd6a5ae1.png)

**Comment by versatran01** [comment]
What I recommend is to run everything else as normal in ros. Then open one camera using flycapture or spinview (you need to install either flycapture or spinnaker sdk). Then you want to check if flycapture/spinview can acquire images at desired framerate (with everything else still running). If yes, then you want to make sure the driver has the same parameters. If no, then this might be a bandwidth issue.

**Comment by ZhiangChen** [comment]
I encountered the same situation. It is not the issue of the driver. I bumped up the frame rate by 
```
rosrun rqt_reconfigure rqt_reconfigure
```
