### ISSUE TITLE
Process has died

### ISSUE THREAD

**Issue by moshanATucsd** [KumarRobotics/flea3#28]
Hi, thanks for the driver! I am using Ubuntu 16.04 with ROS Kinetic, and the single camera case works. However, for stereo case, the error is `[stereo-2] process has died [pid 9105, exit code -11`. I am using the latest flycapture sdk, FlyCapture 2.13.3.31 SDK - Linux Ubuntu 16.04 (64-bit). Could anyone provide some advice?

**Comment by kartikmohta** [comment]
Just to do a quick check, can you try updating the headers and libraries in the `flea3/flycapture/` folder? This package uses it's own bundled version of the SDK to ensure that it is using a known working version but the stereo node hasn't really been tested much.

**Comment by moshanATucsd** [comment]
Thanks for the advice, we think this is related to the default trigger mode of the stereo node. Single node has trigger source = -1 but stereo has trigger source = 7, maybe we need to change this?

**Comment by kartikmohta** [comment]
You need to trigger the cameras in some way to synchronize the stereo pair. Trigger source = 7 just means software triggering, -1 is no trigger. You would want to keep it at 7 unless you're doing some hardware triggering.

**Comment by moshanATucsd** [comment]
Thanks for your reply! We want to do hardware triggering eventually, but right now we are using software triggering. 

We are using the updated headers and libraries, and we find that if we run single node first, then run the stereo node, it works. But if we run the stereo node directly, it won't work. So we suspect that maybe the software triggering is not working.

**Comment by versatran01** [comment]
I recommend using this 
https://github.com/ros-drivers/flir_camera_driver
