### ISSUE TITLE
Flycapture 2.9.3 released

### ISSUE THREAD

**Issue by versatran01** [KumarRobotics/flea3#7]
ptgrey released 2.9.3 SDK.
I tried it but for some reason I have to link to `libusb` manually.
@kartikmohta

**Comment by versatran01** [comment]
It's worse than the previous version.

**Comment by kartikmohta** [comment]
Still doesn't solve the problem of opening two cameras in different processes?

**Comment by versatran01** [comment]
Doesn't even work with one camera now. When I open flycap, image acquisition stops after a few seconds.

**Comment by kartikmohta** [comment]
Aah that's bad.

**Comment by darknight-007** [comment]
Return of the bluefox...
